###
POST http://localhost:3000/simpledex/treinador/cadastrar
Content-Type: application/json

{
    "nome"          :   "teste",
    "email"         :   "teste@teste",
    "senha"         :   "teste123",
    "pokeId"        :   "meuTeste"
}


###
GET http://localhost:3000/simpledex/treinador/listar






###
POST http://localhost:3000/simpledex/pokemon/cadastrar
Content-Type: application/json

{
    "nome"          :   "grimer",
    "descricao"     :   "Grimer, a sludge Pokemon. Born from sludge, these Pokemon specialize in Sludge attacks.",
    "tipo"          :   "poison"
}


###
GET http://localhost:3000/simpledex/pokemon/listar



###
POST http://localhost:3000/simpledex/treinadorPokemon/cadastrar
Content-Type: application/json

{
    "treinador"   :   "608ecc820339e42f80ba4e16",
    "pokemon"     :   "608ecc820339e42f80ba4e16"
}


###
GET http://localhost:3000/simpledex/treinadorPokemon/listar