###
POST http://localhost:3000/simpledex/treinador/cadastrar
Content-Type: application/json

{
    "nome"          :   "teste",
    "email"         :   "teste@teste",
    "senha"         :   "teste123",
    "pokeId"        :   "meuTeste"
}

###
POST http://localhost:3000/simpledex/treinador/cadastrar
Content-Type: application/json

{
    "nome"          :   "teste2",
    "email"         :   "teste2@teste",
    "senha"         :   "teste1234",
    "pokeId"        :   "meuTeste2"
}


###
GET http://localhost:3000/simpledex/treinador/listar






###
POST http://localhost:3000/simpledex/pokemon/cadastrar
Content-Type: application/json

{
    "nome"          :   "grimer",
    "descricao"     :   "Grimer, a sludge Pokemon. Born from sludge, these Pokemon specialize in Sludge attacks.",
    "tipo"          :   "poison"
}

###
POST http://localhost:3000/simpledex/pokemon/cadastrar
Content-Type: application/json

{
    "nome"          :   "Muk",
    "descricao"     :   "Muk, grimer's evolved from. Use extreme caution, as its slimy form contains poison.",
    "tipo"          :   "poison"
}

###
POST http://localhost:3000/simpledex/pokemon/cadastrar
Content-Type: application/json

{
    "nome"          :   "Venonat",
    "descricao"     :   "Venonat, a bug Pokemon. Its eyes function as radar, allowing it to see in the dark.",
    "tipo"          :   "bug"
}

###
POST http://localhost:3000/simpledex/pokemon/cadastrar
Content-Type: application/json

{
    "nome"          :   "Pidgey",
    "descricao"     :   "Pidgey is a flying Pokemon. Among all the Flying Pokémon, it is the gentlest and easiest to capture",
    "tipo"          :   "flying"
}


###
GET http://localhost:3000/simpledex/pokemon/listar



###
POST http://localhost:3000/simpledex/treinadorPokemon/cadastrar
Content-Type: application/json

{
    "treinador"   :   "608ecc820339e42f80ba4e16",
    "pokemon"     :   "608f135a3a413a6510ef951a"
}

###
POST http://localhost:3000/simpledex/treinadorPokemon/cadastrar
Content-Type: application/json

{
    "treinador"   :   "608ecc820339e42f80ba4e16",
    "pokemon"     :   "608f14f73a413a6510ef951f"
}
###
POST http://localhost:3000/simpledex/treinadorPokemon/cadastrar
Content-Type: application/json

{
    "treinador"   :   "608ecc820339e42f80ba4e16",
    "pokemon"     :   "608f14f83a413a6510ef9520"
}

###
POST http://localhost:3000/simpledex/treinadorPokemon/cadastrar
Content-Type: application/json

{
    "treinador"   :   "608f17b09227462c68bf8ac5",
    "pokemon"     :   "608f14f83a413a6510ef9520"
}

###
GET http://localhost:3000/simpledex/treinadorPokemon/listar

###
GET http://localhost:3000/simpledex/treinador/buscar/meuTeste
####
GET http://localhost:3000/simpledex/treinador/remover/meuTeste2

#####
POST http://localhost:3000/simpledex/treinador/alterar/meuTeste



####
GET http://localhost:3000/simpledex/pokemon/buscar/grimer


####
GET http://localhost:3000/simpledex/pokemon/buscarPorTipo/poison


######
GET http://localhost:3000/simpledex/pokemon/remover/grimer




###
GET http://localhost:3000/simpledex/treinadorPokemon/listarPokemon/meuTeste

###
GET http://localhost:3000/simpledex/treinadorPokemon/listarPokemon/meuTeste2


###
GET http://localhost:3000/simpledex/treinadorPokemon/listarTreinadores/grimer


###
GET http://localhost:3000/simpledex/treinadorPokemon/listarTreinadores/Pidgey


###
GET http://localhost:3000/simpledex/treinadorPokemon/contarPokemonPorTipo/meuTeste


###
GET http://localhost:3000/simpledex/treinadorPokemon/contarPokemon/meuTeste


###
GET http://localhost:3000/simpledex/treinadorPokemon/contarPokemonPorTipo/meuTeste2


###
GET http://localhost:3000/simpledex/treinadorPokemon/contarPokemon/meuTeste2
